version: 2

builds:
  - main: .
    binary: bmgr
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: davidpanter
      name: homebrew-tap
    homepage: https://github.com/davidpanter/bmgr
    description: Terminal keybinding manager with fzf
    license: BSD-2-Clause
    dependencies:
      - name: fzf

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
